### ISSUE TITLE
ZKIT

### ISSUE THREAD

**Issue by MBrants** [000Zer000/ZKit-Framework#11]
Trying to run Zkit on Kali linux latest build,
Installed python 3.8.5

but when i run Zkit i will get this message.

```
server@ptr-5el9zzr8l1to6vap423:~/Desktop/ZKit-Framework$ python3 zkit.py 
Traceback (most recent call last):
  File "zkit.py", line 14, in <module>
    from ui_core._core import Generate, init, print_banner, crash_handler
  File "/home/server/Desktop/ZKit-Framework/ui_core/_core.py", line 37
    os.popen(f'touch {path + "/Errors.log}"')
             ^
SyntaxError: f-string: expecting '}'


```

**Comment by 000Zer000** [comment]
Im sorry you are right . I will fix it right now .

Have Fun !

**Comment by 000Zer000** [comment]
I have commited a fix . i hope it is the fix that was needed

Have Fun !

**Comment by MBrants** [comment]
Thanks that problem is fixed, great!
But right now i got a another problem, here the code that i get:

```
..> 2

{1} --> python_ransomware_tcp >>> lib/payloads/ransomware/python_ransomware_tcp                                                                                       

{2} --> python_ransomware_udp >>> lib/payloads/ransomware/python_ransomware_udp                                                                                       

{000} --> Back To Main Menu
Please Choose One Of Them (Number Of It): 2
Sth went really wrong that we couldnt handle it
the exceptions value have saved to Errors.log
please report this on github to me.Do you want zkit to reraise it ? (reraising may help better) (Y/N): Y
This is going to print full error . please report it on github
Traceback (most recent call last):
  File "zkit.py", line 115, in <module>
    crash_handler(e)
  File "zkit.py", line 111, in <module>
    starter.main_loop()
  File "zkit.py", line 104, in main_loop
    self.execute(choice)
  File "zkit.py", line 84, in execute
    self._execute_payload_related(choice)
  File "zkit.py", line 80, in _execute_payload_related
    list_builtin_payloads_helper(choice)
  File "zkit.py", line 38, in list_builtin_payloads_helper
    Generate(list(payloads.values())[int(index) - 1])
  File "/home/server/Desktop/ZKit-Framework-master/ui_core/_core.py", line 66, in __init__
    self.pg = PayloadGenerator(self.root)
  File "/home/server/Desktop/ZKit-Framework-master/lib/payload.py", line 98, in __init__
    AntiMalware(self.root + payload + ".py")
  File "/home/server/Desktop/ZKit-Framework-master/lib/payload.py", line 32, in __init__
    self.fd = self.remove_comments(fd)
AttributeError: 'AntiMalware' object has no attribute 'remove_comments'
```

**Comment by 000Zer000** [comment]
Let me check it out . I will commit a fix for it . All the versions were tested but not this version . so it might happen .

**Comment by 000Zer000** [comment]
Here you go 

Have Fun !

**Comment by 000Zer000** [comment]
If its fixed please close this issue
