### ISSUE TITLE
ERROR 09

### ISSUE THREAD

**Issue by MBrants** [000Zer000/ZKit-Framework#13]
Here the error code,

```
Traceback (most recent call last):
  File "zkit.py", line 115, in <module>
    crash_handler(e)
  File "zkit.py", line 111, in <module>
    starter.main_loop()
  File "zkit.py", line 104, in main_loop
    self.execute(choice)
  File "zkit.py", line 84, in execute
    self._execute_payload_related(choice)
  File "zkit.py", line 80, in _execute_payload_related
    list_builtin_payloads_helper(choice)
  File "zkit.py", line 38, in list_builtin_payloads_helper
    Generate(list(payloads.values())[int(index) - 1])
  File "/home/server/Desktop/ZKit-Framework-master/ui_core/_core.py", line 66, in __init__
    self.pg = PayloadGenerator(self.root)
  File "/home/server/Desktop/ZKit-Framework-master/lib/payload.py", line 102, in __init__
    self.payloads[payload] = imp(
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
```

**Comment by 000Zer000** [comment]
Im closing this issue because you didnt respond . if the problem still persists . please reopen this . I'm at all service for ZKit
